// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ContactAPI.Core.Entities.Base;
using System;
using System.Collections.Generic;

namespace ContactAPI.Core.Entities
{
    public partial class Contact: BaseEntity
    {
        public Contact()
        {
            Address = new HashSet<Address>();
            Date = new HashSet<Date>();
            Email = new HashSet<Email>();
            InstantMessage = new HashSet<InstantMessage>();
            Phone = new HashSet<Phone>();
            SocialProfile = new HashSet<SocialProfile>();
            Url = new HashSet<Url>();
        }

        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Type { get; set; }
        public string Role { get; set; }
        public long? CreatedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public string Avatar { get; set; }
        public string RingTone { get; set; }
        public string TextTone { get; set; }
        public DateTime? BirthDay { get; set; }
        public string Note { get; set; }
        public byte? RowStatusId { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Date> Date { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<InstantMessage> InstantMessage { get; set; }
        public virtual ICollection<Phone> Phone { get; set; }
        public virtual ICollection<SocialProfile> SocialProfile { get; set; }
        public virtual ICollection<Url> Url { get; set; }
    }
}